version: '2.2'
services:
  aula2:
    container_name: aula-2
    image: oficina-docker:aula2-volumes
    build: .
    ports:
      - 5020:5000
    volumes:
      - .:/usr/src
      - aula2-logs:/tmp   

  nginx: 
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80

  db:
    container_name: postgres
    image: postgres:9.6
    ports:
      - 5432:5432

  cache:
    container_name: memcached
    image: memcached

volumes:
  aula2-logs:

